### ISSUE TITLE
Alpine: which store to use?

### ISSUE THREAD

**Issue by emillon** [mirage/ca-certs#5]
Alpine has some differences between the openssl path and /etc/ssl/cert.pem. What are these differences and is it ok to use the openssl path if present?

**Comment by hannesm** [comment]
the CI works fine with alpine, I'll close this issue until someone runs into the mentioned issue. It may at some point make sense to be more strict for Linux distributions by looking up only a single path for each distribution (instead of the current approach, where a list of locations is used, and once one is present on the file system, it is used).
